import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";
import LanguageToggle from "@/components/LanguageToggle";
import { currentUser } from "@/lib/auth";
import { languageFromCookie, type Language } from "@/lib/i18n";
import { listTransfers } from "@/lib/store";

export const dynamic = "force-dynamic";

export default async function RecordsPage() {
  const user = await currentUser();
  if (!user) redirect("/login");
  const language = languageFromCookie((await cookies()).get("flowpilot_lang")?.value);
  const transfers = listTransfers(user.id); const live = transfers.filter((t) => !t.simulated); const total = transfers.reduce((sum, t) => sum + t.amount_usdc, 0); const en = language === "en";
  return <main className="mx-auto max-w-[46rem] px-4 pb-16 sm:px-6"><header className="material-chrome sticky top-0 z-20 -mx-4 flex items-center gap-3 px-4 py-3 sm:-mx-6 sm:px-6"><Link href="/" aria-label={en ? "Back to chat" : "返回对话"} className="pressable material-chip grid h-8 w-8 place-items-center rounded-[10px] text-label-2">←</Link><div className="min-w-0 flex-1"><h1 className="type-display">{en ? "Execution records" : "执行记录"}</h1><p className="type-caption text-label-2">{en ? `Compliance audit trail · ${user.email}` : `合规审计轨迹 · ${user.email}`}</p></div><LanguageToggle language={language} /></header><section className="animate-materialize mt-4 grid grid-cols-3 gap-2"><Stat label={en ? "Total" : "总笔数"} value={String(transfers.length)} /><Stat label={en ? "Live" : "真实执行"} value={String(live.length)} tone={live.length ? "green" : undefined} /><Stat label={en ? "Volume" : "累计金额"} value={total.toFixed(2)} sub="USDC" /></section>{transfers.length === 0 ? <div className="material-card animate-materialize mt-3 rounded-card px-4 py-10 text-center"><p className="text-[0.9375rem] text-label-2">{en ? "No execution records yet" : "还没有执行记录"}</p><p className="type-caption mt-1 text-label-3">{en ? "Complete a transfer in chat and its audit trail will appear here." : "在对话中完成一次转账后，审计记录会显示在这里。"}</p><Link href="/" className="pressable mt-4 inline-block rounded-full bg-blue px-4 py-2 text-[0.8125rem] font-medium text-white">{en ? "Start a conversation" : "开始对话"}</Link></div> : <ol className="mt-3 space-y-2">{transfers.map((t, i) => <li key={t.id} className="material-card animate-materialize rounded-card px-4 py-3" style={{ animationDelay: `${Math.min(i, 8) * 45}ms` }}><div className="flex items-baseline justify-between gap-3"><p className="tnum text-[1.125rem] font-semibold">{t.amount_usdc}<span className="ml-1 text-[0.8125rem] font-medium text-label-2">USDC</span></p><div className="flex shrink-0 items-center gap-1.5">{t.screened_ok && <span className="type-caption rounded-full border border-green/25 bg-green/12 px-2 py-0.5 text-green">{en ? "Screened" : "已筛查"}</span>}<span className={`type-caption rounded-full border px-2 py-0.5 font-medium ${t.simulated ? "border-orange/30 bg-orange/12 text-orange" : "border-green/30 bg-green/12 text-green"}`}>{t.simulated ? (en ? "Simulated" : "模拟") : (en ? "Broadcast" : "已广播")}</span></div></div><dl className="mt-2 space-y-1"><Row label={en ? "To" : "收款"} value={t.to_address} /><Row label={en ? "Hash" : "哈希"} value={t.tx_hash} /><Row label={en ? "Time" : "时间"} value={new Date(t.created_at).toLocaleString(en ? "en-US" : "zh-TW")} plain /></dl>{t.explorer_url && <a href={t.explorer_url} target="_blank" rel="noreferrer" className="pressable mt-2.5 inline-flex items-center gap-1.5 rounded-full bg-green/15 px-3 py-1.5 text-[0.8125rem] font-medium text-green hover:bg-green/22">{en ? "View on BaseScan" : "在 BaseScan 查看"} <span aria-hidden>→</span></a>}</li>)}</ol>}</main>;
}

function Stat({ label, value, sub, tone }: { label: string; value: string; sub?: string; tone?: "green" }) { return <div className="material-card rounded-card px-3 py-2.5"><p className={`tnum text-[1.25rem] font-semibold leading-tight ${tone === "green" ? "text-green" : "text-label"}`}>{value}{sub && <span className="ml-1 text-[0.75rem] font-medium text-label-2">{sub}</span>}</p><p className="type-caption mt-0.5 text-label-3">{label}</p></div>; }
function Row({ label, value, plain }: { label: string; value: string; plain?: boolean }) { return <div className="flex items-baseline gap-2.5"><dt className="type-caption w-16 shrink-0 text-label-3">{label}</dt><dd className={`min-w-0 break-all text-label-2 ${plain ? "tnum text-[0.75rem]" : "tnum font-mono text-[0.6875rem]"}`}>{value}</dd></div>; }
