import type { Language } from "@/lib/i18n";
import type { FxForecast } from "@/lib/types";
import { CardHeader } from "./IntentCard";

export default function FxForecastCard({ forecast, language }: { forecast: FxForecast; language: Language }) {
  const en = language === "en"; const wait = forecast.recommendation === "wait"; const vols = forecast.vol_series.map((v) => v.vol_ann_pct); const min = Math.min(...vols); const max = Math.max(...vols); const range = max - min || 1;
  const rationale = en
    ? `${forecast.pair} has ${wait ? "higher" : "contained"} expected volatility over the next seven days. The 95% confidence range is ±${forecast.ci95_high_pct}%, so ${wait ? "watching or splitting the transfer is safer if the deadline allows" : "the lowest-cost route can be executed now"}.`
    : `${forecast.pair} 未来 7 天预期波动${wait ? "较高" : "可控"}，95% 置信区间为 ±${forecast.ci95_high_pct}%；${wait ? "若期限允许，建议观察或分批执行" : "可以现在执行成本最低的路线"}。`;
  return <section className="material-card rounded-card px-4 py-3.5"><CardHeader step="M3" title={en ? "FX timing advice" : "汇率时机建议"} note={en ? `${forecast.model.split(" ")[0]} volatility model` : `${forecast.model.split(" ")[0]} 波动率模型`} accent={<span className={`type-caption rounded-full border px-2 py-0.5 font-medium ${wait ? "border-orange/30 bg-orange/12 text-orange" : "border-green/25 bg-green/12 text-green"}`}>{wait ? (en ? "Consider waiting" : "建议观望") : (en ? "Act now" : "建议执行")}</span>} /><div className="mt-3 grid grid-cols-3 gap-1.5"><Stat label={`${forecast.pair} ${en ? "spot" : "即期"}`} value={String(forecast.spot)} /><Stat label={en ? "7d forecast vol" : "7日预测波动"} value={`${forecast.forecast_vol_7d_ann_pct}%`} sub={en ? "annualized" : "年化"} /><Stat label={en ? "95% CI" : "95%区间"} value={`±${forecast.ci95_high_pct}%`} tone={wait ? "orange" : "green"} /></div><figure className="mt-3"><div className="flex h-14 items-end gap-[3px]" role="img" aria-label={en ? "30-day volatility history" : "30 日历史波动率"}>{forecast.vol_series.map((v, i) => <div key={v.date} title={`${v.date} · ${v.vol_ann_pct}%`} className={`flex-1 rounded-t-[3px] ${i === forecast.vol_series.length - 1 ? "bg-jade" : "bg-jade/35"}`} style={{ height: `${22 + ((v.vol_ann_pct - min) / range) * 78}%` }} />)}</div><figcaption className="type-caption mt-1.5 flex justify-between text-label-3"><span>{en ? "30-day annualized volatility" : "30 日年化波动率"}</span><span className="tnum">{en ? "As of" : "截至"} {forecast.asof}</span></figcaption></figure><p className="mt-2.5 text-[0.8125rem] leading-relaxed text-label-2">{rationale}</p></section>;
}

function Stat({ label, value, sub, tone }: { label: string; value: string; sub?: string; tone?: "green" | "orange" }) { const color = tone === "orange" ? "text-orange" : tone === "green" ? "text-green" : "text-label"; return <div className="material-chip rounded-[12px] px-2.5 py-2"><p className={`tnum text-[1.0625rem] font-semibold leading-tight ${color}`}>{value}</p><p className="type-caption mt-0.5 truncate text-label-3">{label}{sub && <span className="ml-1 opacity-70">{sub}</span>}</p></div>; }
