import type { Language } from "@/lib/i18n";
import type { Route, RoutesResult } from "@/lib/types";
import { CardHeader } from "./IntentCard";

export default function RouteCard({ result, language }: { result: RoutesResult; language: Language }) {
  if (!result?.routes?.length) return null;
  const en = language === "en"; const best = result.routes[0]; const worst = result.routes.reduce((a, b) => b.total_cost_pct > a.total_cost_pct ? b : a); const saved = worst.total_cost_amount - best.total_cost_amount; const maxPct = worst.total_cost_pct || 1;
  return <section className="material-card rounded-card px-4 py-3.5"><CardHeader step="M2" title={en ? "Route comparison" : "路径比价"} note={result.source === "mock" ? "Mock data" : "LI.FI live quote"} accent={saved > 0 ? <span className="tnum type-caption rounded-full border border-green/25 bg-green/12 px-2 py-0.5 font-medium text-green">{en ? `Save ${saved.toLocaleString()} ${result.from_currency}` : `最多省 ${saved.toLocaleString()} ${result.from_currency}`}</span> : null} />{result.source === "mock" && <p className="type-caption mt-2 rounded-lg border border-orange/25 bg-orange/10 px-2.5 py-1.5 text-orange">{en ? "Demo estimate, not a live quote. Do not use it as a final financial decision." : "演示估算，不是实时报价；请勿据此直接做资金决策。"}</p>}{result.source_note && <p className="type-caption mt-2 text-label-3">Source: {result.source_note}{result.quoted_at ? ` · ${new Date(result.quoted_at).toLocaleTimeString(en ? "en-US" : "zh-TW")}` : ""}</p>}<ol className="mt-3 space-y-1.5">{result.routes.map((r) => <RouteRow key={r.id} route={r} currency={result.from_currency} isBest={r.id === best.id} widthPct={(r.total_cost_pct / maxPct) * 100} language={language} />)}</ol></section>;
}

function RouteRow({ route, currency, isBest, widthPct, language }: { route: Route; currency: string; isBest: boolean; widthPct: number; language: Language }) {
  const en = language === "en"; const tradfi = route.kind === "tradfi";
  return <li className={`relative overflow-hidden rounded-[12px] border px-3 py-2.5 ${isBest ? "border-green/30 bg-green/[0.07]" : tradfi ? "border-white/6 bg-white/[0.02]" : "border-white/8 bg-white/[0.035]"}`}><div aria-hidden className={`absolute inset-y-0 left-0 ${isBest ? "bg-green/10" : "bg-white/[0.035]"}`} style={{ width: `${widthPct}%` }} /><div className="relative flex items-center gap-3"><div className="min-w-0 flex-1"><p className="flex items-center gap-1.5 truncate text-[0.875rem] font-medium text-label">{isBest && <span className="type-caption rounded bg-green/20 px-1.5 py-px font-semibold text-green">{en ? "Best" : "推荐"}</span>}<span className={tradfi ? "text-label-2" : ""} title={route.label}>{!tradfi && !en ? `数字结算通道 · ${route.chain ?? route.bridge_or_provider}` : route.label}</span></p><p className="type-caption mt-0.5 truncate text-label-3">{route.notes}</p></div><div className="shrink-0 text-right"><p className={`tnum text-[0.9375rem] font-semibold leading-tight ${isBest ? "text-green" : tradfi ? "text-label-2" : "text-label"}`}>{route.total_cost_pct.toFixed(2)}%</p><p className="tnum type-caption text-label-3">{route.total_cost_amount.toLocaleString()} {currency} · {formatEta(route.eta_minutes, language)}</p></div></div></li>;
}

function formatEta(min: number, language: Language) { const en = language === "en"; if (min < 60) return en ? `${min} min` : `${min} 分钟`; if (min < 60 * 24) return en ? `${Math.round(min / 60)} hr` : `${Math.round(min / 60)} 小时`; return en ? `${Math.round(min / 60 / 24)} days` : `${Math.round(min / 60 / 24)} 天`; }
